language: java
jdk:
  - openjdk7
before_script:
  - sudo apt-get update
  - sudo apt-get update && sudo apt-get install git-core gnupg flex bison gperf libsdl1.2-dev libesd0-dev libwxgtk2.8-dev squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev openjdk-6-jre openjdk-6-jdk pngcrush schedtool libxml2 libxml2-utils xsltproc lzop libc6-dev schedtool g++-multilib lib32z1-dev lib32ncurses5-dev lib32readline-gplv2-dev gcc-multilib
script:
  - repo init -u https://github.com/MoKee/android.git -b mkl-mr1
  - repo sync 
  - source build/envsetup.sh
  - lunch mk_cancro-userdebug
  - make bacon  